- name: Install PostgreSQL
  ansible.builtin.package:
    name: postgresql-server
    state: present

- name: Initialize DB
  shell: postgresql-setup initdb
  become: yes

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Set up schema
  become_user: postgres
  postgresql_db:
    name: sharedappdb

- name: Copy DB schema to remote
  copy:
    src: shared_db/init.sql
    dest: /tmp/init.sql
  become: yes

- name: Load schema
  become_user: postgres
  command: psql -d sharedappdb -f /tmp/init.sql
