
- name: Check if PostgreSQL is initialized
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgdata_initialized
  become: yes

- name: Initialize PostgreSQL database if not already initialized
  command: postgresql-setup --initdb
  become: yes
  when: not pgdata_initialized.stat.exists

- name: Start and enable PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create the database 'sharedappdb' if it doesn't exist
  become: yes
  become_user: postgres
  postgresql_db:
    name: sharedappdb
    state: present

- name: Copy DB schema to remote
  copy:
    src: shared_db/init.sql
    dest: /tmp/init.sql
  become: yes

- name: Load schema into sharedappdb
  become_user: postgres
  command: psql -d sharedappdb -f /tmp/init.sql
