---
- name: Setup and Deploy Dual App to Shared Host
  hosts: app
  become: yes

  pre_tasks:
    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add SSH user to Docker group (non-fatal if already added)
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes
      ignore_errors: true

    - name: Reset SSH connection to apply docker group changes
      meta: reset_connection

  roles:
    - postgresql
    - flask_app
    - node_app
