---
# tasks file for roles/node_app
- name: Pull Node image
  community.docker.docker_image:
    name: node_app
    source: build
    build:
      path: /home/fedora/dual-app/node_app
  environment:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  become: yes
  become_user: fedora

- name: Run Node container
  community.docker.docker_container:
    name: node_app
    image: node_app
    state: started
    restart_policy: always
    published_ports:
      - "3000:3000"
  environment:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  become: yes
  become_user: fedora