---
- name: Create extract directory for Node image
  file:
    path: "/tmp/node_app"
    state: directory
    mode: '0755'

- name: Download Node image artifact from Nexus
  get_url:
    url: "http://34.227.49.233:8081/repository/dual-app-artifacts/node_app-{{ version }}.tar.gz"
    dest: "/tmp/node_app-{{ version }}.tar.gz"
    mode: '0644'
    url_username: "{{ nexus_user }}"
    url_password: "{{ nexus_pass }}"

- name: Extract Node image archive
  unarchive:
    src: "/tmp/node_app-{{ version }}.tar.gz"
    dest: "/tmp/node_app"
    remote_src: yes

- name: Build Node image from extracted files
  command: docker build -t node_app:{{ version }} .
  args:
    chdir: /tmp/node_app/node_app
  become: yes
  become_user: fedora

- name: Stop & remove old Node container (if exists)
  shell: docker rm -f node_app || true
  ignore_errors: true
  become: yes
  become_user: fedora

- name: Run Node container using Docker CLI
  command: >
    docker run -d --name node_app
    --restart always
    -p 3000:3000
    node_app:{{ version }}
  args:
    warn: false
  become: yes
  become_user: fedora
