---
# tasks file for roles/node_app
- name: Download Node image artifact from Nexus (public IP)
  get_url:
    url: "http://34.227.49.233:8081/repository/dual-app-artifacts/node_app-{{ version }}.tar.gz"
    dest: "/tmp/node_app-{{ version }}.tar.gz"
    mode: '0644'
    url_username: "{{ nexus_user }}"
    url_password: "{{ nexus_pass }}"

- name: Extract Node image archive
  unarchive:
    src: "/tmp/node_app-{{ version }}.tar.gz"
    dest: "/tmp/node_app"
    remote_src: yes

- name: Load Node image into Docker
  command: docker build -t node_app:{{ version }} .
  args:
    chdir: /tmp/node_app

- name: Run Node container
  community.docker.docker_container:
    name: node_app
    image: node_app:{{ version }}
    state: started
    restart_policy: always
    published_ports:
      - "3000:3000"
  become: yes
  become_user: fedora