---
# tasks file for roles/flask_app
- name: Pull Flask image
  community.docker.docker_image:
    name: flask_app
    source: build
    build:
      path: /home/fedora/dual-app/flask_app
    docker_host: "unix://var/run/docker.sock"

- name: Run Flask container
  community.docker.docker_container:
    name: flask_app
    image: flask_app
    state: started
    restart_policy: always
    published_ports:
      - "5000:5000"
    env:
      DB_HOST: localhost
      DB_NAME: sharedappdb
      DB_USER: devops
      DB_PASS: admin123
    docker_host: "unix://var/run/docker.sock"